package ru.sfedu.projectmanager.model.enums;


public enum ResultType {
    SUCCESSFUL,
    IO_EXCEPTION,
    SQL_EXCEPTION,
    INTEGRITY_CONSTRAIN_EXCEPTION,
    COMMUNICATIONS_EXCEPTION,
    EXCEPTION,
    FILE_NOT_FOUND_EXCEPTION,

    LOGIN_NOT_EXIST,
    LOGIN_ALREADY_EXIST,
    TITLE_NOT_EXIST,
    TITLE_ALREADY_EXIST,
    ID_ALREADY_EXIST,
    ID_NOT_EXIST,

}
